#!/usr/bin/env node

const solver = require("./src/8queens.js");

const board = [0, 6, 4, 7, 1, 3, 5, 2];
console.log(solver.board_string(board));
console.log(solver.is_valid(board));

console.log(solver.find_all_solutions());
