#!/usr/bin/env node

const eight_queens = require("./src/8queens.js");

const solutions = eight_queens.find_all_solutions();

solutions
    .map(eight_queens.board_to_string)
    .forEach(s => console.log(s));

console.log(`Found ${solutions.length} solutions`);
